# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :cov do
    # add actions here: https://docs.fastlane.tools/actions
    scan(
       workspace: "AirService.xcworkspace",
       scheme: "AirService",
       output_directory: "scan_output"
    )
    xcov(
       workspace: "AirService.xcworkspace",
       scheme: "AirService",
       output_directory: "xcov_output",
       only_project_targets: true,
       source_directory: "AirService",
       ignore_file_path: ".xcovignore"
    )
  end
end
